Repository LikeKNU/LikeKNU-JobServer, pull requests merged in 2023-10, with the labels that each got.

#15 Fix: 캐시 사이즈 조절
  src/main/java/ac/knu/likeknujobserver/announcement/service/AnnouncementService.java
Labels: 🐛Bug, 🛠️BackEnd

#14 학사일정 db 저장
  src/main/java/ac/knu/likeknujobserver/calendar/domain/AcademicCalendar.java
  src/main/java/ac/knu/likeknujobserver/calendar/dto/AcademicCalendarMessage.java
  src/main/java/ac/knu/likeknujobserver/calendar/repository/AcademicCalendarRepository.java
  src/main/java/ac/knu/likeknujobserver/calendar/service/AcademicCalendarConsumer.java
  src/main/java/ac/knu/likeknujobserver/calendar/service/AcademicCalendarService.java
  src/main/java/ac/knu/likeknujobserver/common/value/Domain.java
  src/main/java/ac/knu/likeknujobserver/menu/service/MenuConsumer.java
  src/main/java/ac/knu/likeknujobserver/menu/service/MenuService.java
Labels: 💫Feature, 🛠️BackEnd

#16 Fix: 중복 저장 오류 수정, equals, hashcode 재정의
  src/main/java/ac/knu/likeknujobserver/menu/service/MenuService.java
Labels: 🐛Bug, 🛠️BackEnd

#19 Fix: cafeteria를 매개변수로 전달하도록 수정
  src/main/java/ac/knu/likeknujobserver/menu/dto/MenuMessage.java
  src/main/java/ac/knu/likeknujobserver/menu/repository/MenuRepository.java
  src/main/java/ac/knu/likeknujobserver/menu/service/MenuService.java
Labels: 🛠️BackEnd
